export type RootStackParamList = {
  Splash: undefined;
  Connection: undefined;
  Login: undefined;
  WelcomeInfluenceur: undefined;
  WelcomeCommercant: undefined;
  CreatorInfluenceur: undefined;
  CreatorCommercant: undefined;
  InterestStep: undefined;
  SocialConnectStep: undefined;
  PortfolioStep: undefined;
  Home: undefined;
  Profile: undefined;
  Messages: undefined;
  Chat: { userId: string };
  Notifications: undefined;
  Search: undefined;
  CampaignDetails: { campaignId: string };
  Settings: undefined;
}; 