export type RootStackParamList = {
  // Pages de connexion
  Splash: undefined;
  Connection: undefined;
  WelcomeInfluenceur: undefined;
  WelcomeCommercant: undefined;
  CreatorTypeInfluenceur: undefined;
  ConceptInfluenceur: undefined;
  LoginOrConnect: undefined;
  Login: undefined;
  Register: undefined;
  ValidateInscription: undefined;
  RegistrationStepOne: undefined;
  InterestStep: undefined;
  SocialConnect: undefined;
  PortfolioStep: undefined;
  RegistrationComplete: undefined;
  DealsInfluenceur: undefined;
  SuivisDealsInfluenceur: undefined;
  DiscussionInfluenceur: undefined;
  SaveDealsInfluenceur: undefined;
  ProfileInfluenceur: undefined;
  ChatInfluenceur: undefined;
  DealDetailsInfluenceur: undefined; // { deal: Deal };
  DealsSeeMoreInfluenceur: undefined;
  ConceptCommercant: undefined;
  CreatorCommercant: undefined;
  DealsCommercant: undefined;
  ForgotPassword: undefined;
  DealsCreation: undefined;
  MerchantDetailCommercant: undefined;
  DealCandidatesCommercant: undefined //{ dealId: string };
  DealsCreationCommercant: undefined;
  ProfileCommercant: undefined;
  SuiviDealsCommercant: undefined;
  DiscussionCommercant: undefined;
  DashboardCommercant: undefined;
}; 
